name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # We need to merge this to one step to ensure node-sass has correct bindings in order to run tests
      # otherwise will result in node-sass not getting correct setup for running
      - name: Install & Test
        run: |
          nvm install
          npm ci
          nvm use
          npm test
